name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        make
        strip -p dsmtk
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: dsmtk
        compression-level: 9
        path: dsmtk
